# Generated by Django 4.2.2 on 2023-07-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
